package com.yjm.doctor.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.yjm.doctor.model.Customer;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CUSTOMER".
*/
public class CustomerDao extends AbstractDao<Customer, Integer> {

    public static final String TABLENAME = "CUSTOMER";

    /**
     * Properties of entity Customer.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Age = new Property(0, int.class, "age", false, "AGE");
        public final static Property Balance = new Property(1, float.class, "balance", false, "BALANCE");
        public final static Property Birthday = new Property(2, long.class, "birthday", false, "BIRTHDAY");
        public final static Property GroupId = new Property(3, int.class, "groupId", false, "GROUP_ID");
        public final static Property Phone = new Property(4, String.class, "phone", false, "PHONE");
        public final static Property Point = new Property(5, int.class, "point", false, "POINT");
        public final static Property RealName = new Property(6, String.class, "realName", false, "REAL_NAME");
        public final static Property Sex = new Property(7, int.class, "sex", false, "SEX");
        public final static Property UserId = new Property(8, int.class, "userId", true, "USER_ID");
    }


    public CustomerDao(DaoConfig config) {
        super(config);
    }
    
    public CustomerDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CUSTOMER\" (" + //
                "\"AGE\" INTEGER NOT NULL ," + // 0: age
                "\"BALANCE\" REAL NOT NULL ," + // 1: balance
                "\"BIRTHDAY\" INTEGER NOT NULL ," + // 2: birthday
                "\"GROUP_ID\" INTEGER NOT NULL ," + // 3: groupId
                "\"PHONE\" TEXT," + // 4: phone
                "\"POINT\" INTEGER NOT NULL ," + // 5: point
                "\"REAL_NAME\" TEXT," + // 6: realName
                "\"SEX\" INTEGER NOT NULL ," + // 7: sex
                "\"USER_ID\" INTEGER PRIMARY KEY NOT NULL );"); // 8: userId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CUSTOMER\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Customer entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getAge());
        stmt.bindDouble(2, entity.getBalance());
        stmt.bindLong(3, entity.getBirthday());
        stmt.bindLong(4, entity.getGroupId());
 
        String phone = entity.getPhone();
        if (phone != null) {
            stmt.bindString(5, phone);
        }
        stmt.bindLong(6, entity.getPoint());
 
        String realName = entity.getRealName();
        if (realName != null) {
            stmt.bindString(7, realName);
        }
        stmt.bindLong(8, entity.getSex());
        stmt.bindLong(9, entity.getUserId());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Customer entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getAge());
        stmt.bindDouble(2, entity.getBalance());
        stmt.bindLong(3, entity.getBirthday());
        stmt.bindLong(4, entity.getGroupId());
 
        String phone = entity.getPhone();
        if (phone != null) {
            stmt.bindString(5, phone);
        }
        stmt.bindLong(6, entity.getPoint());
 
        String realName = entity.getRealName();
        if (realName != null) {
            stmt.bindString(7, realName);
        }
        stmt.bindLong(8, entity.getSex());
        stmt.bindLong(9, entity.getUserId());
    }

    @Override
    public Integer readKey(Cursor cursor, int offset) {
        return cursor.getInt(offset + 8);
    }    

    @Override
    public Customer readEntity(Cursor cursor, int offset) {
        Customer entity = new Customer( //
            cursor.getInt(offset + 0), // age
            cursor.getFloat(offset + 1), // balance
            cursor.getLong(offset + 2), // birthday
            cursor.getInt(offset + 3), // groupId
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // phone
            cursor.getInt(offset + 5), // point
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // realName
            cursor.getInt(offset + 7), // sex
            cursor.getInt(offset + 8) // userId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Customer entity, int offset) {
        entity.setAge(cursor.getInt(offset + 0));
        entity.setBalance(cursor.getFloat(offset + 1));
        entity.setBirthday(cursor.getLong(offset + 2));
        entity.setGroupId(cursor.getInt(offset + 3));
        entity.setPhone(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setPoint(cursor.getInt(offset + 5));
        entity.setRealName(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setSex(cursor.getInt(offset + 7));
        entity.setUserId(cursor.getInt(offset + 8));
     }
    
    @Override
    protected final Integer updateKeyAfterInsert(Customer entity, long rowId) {
        return entity.getUserId();
    }
    
    @Override
    public Integer getKey(Customer entity) {
        if(entity != null) {
            return entity.getUserId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Customer entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
